CREATE TABLE IF NOT EXISTS pokemon (
	dex INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT COLLATE BINARY,
	dex_limit INTEGER NOT NULL COLLATE BINARY,
	dex_version INTEGER COLLATE BINARY,
	region TEXT,
	gen INTEGER NOT NULL COLLATE BINARY,
	species TEXT NOT NULL,
	mega INTEGER NOT NULL COLLATE BINARY, 
	alolan INTEGER NOT NULL COLLATE BINARY,
	galarian INTEGER NOT NULL COLLATE BINARY,
	gmax INTEGER NOT NULL COLLATE BINARY,
	forme TEXT
);

CREATE TABLE IF NOT EXISTS pokedex (
	row INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT COLLATE BINARY,
	species INTEGER NOT NULL COLLATE BINARY,
	version INTEGER NOT NULL COLLATE BINARY,
	language INTEGER NOT NULL COLLATE BINARY,
	text TEXT
);